package view;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author admin
 */
public class User_pannel extends javax.swing.JFrame {

    static int x = 10;

    /**
     * Creates new form Burger_ordering_system
     */
    public User_pannel() {
        initComponents();
    }

    DefaultTableModel model;
    String item;
    int price;

    Connection con;
    PreparedStatement pst;
    PreparedStatement pst1;
    PreparedStatement pst2;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        beefrad = new javax.swing.JRadioButton();
        chickenrad = new javax.swing.JRadioButton();
        veggierad = new javax.swing.JRadioButton();
        turkeyrad = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        bunlbl = new javax.swing.JLabel();
        mildrad = new javax.swing.JRadioButton();
        spicyrad = new javax.swing.JRadioButton();
        veryspicyrad = new javax.swing.JRadioButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        saladlvl = new javax.swing.JLabel();
        cheeseck = new javax.swing.JCheckBox();
        eggck = new javax.swing.JCheckBox();
        extrack = new javax.swing.JCheckBox();
        jPanel11 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        saucelbl = new javax.swing.JLabel();
        lessrad = new javax.swing.JRadioButton();
        regularrad = new javax.swing.JRadioButton();
        morerad = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        quantitylbl = new javax.swing.JLabel();
        quantitytxt = new javax.swing.JSpinner();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        balancetxt = new javax.swing.JTextField();
        paymenttxt = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        Total = new javax.swing.JLabel();
        totaltxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 4));

        jLabel1.setFont(new java.awt.Font("Gloucester MT Extra Condensed", 3, 60)); // NOI18N
        jLabel1.setText("WELCOME TO HOTFOOD");

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        beefrad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        beefrad.setText("Beef Burger tk 100");
        beefrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beefradActionPerformed(evt);
            }
        });

        chickenrad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        chickenrad.setText("Chicken Burger tk 90");
        chickenrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chickenradActionPerformed(evt);
            }
        });

        veggierad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        veggierad.setText("Pasta tk 250");
        veggierad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veggieradActionPerformed(evt);
            }
        });

        turkeyrad.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        turkeyrad.setText("Special Pizza 12' tk 500");
        turkeyrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                turkeyradActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("FOOD");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(veggierad)
                    .addComponent(turkeyrad)
                    .addComponent(beefrad)
                    .addComponent(chickenrad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(beefrad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(chickenrad)
                .addGap(27, 27, 27)
                .addComponent(veggierad)
                .addGap(31, 31, 31)
                .addComponent(turkeyrad)
                .addGap(17, 17, 17))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        bunlbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bunlbl.setText("Spice Level");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(bunlbl)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(bunlbl)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        mildrad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mildrad.setText("Mild");
        mildrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mildradActionPerformed(evt);
            }
        });

        spicyrad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spicyrad.setText("Spicy");
        spicyrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spicyradActionPerformed(evt);
            }
        });

        veryspicyrad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        veryspicyrad.setText("Very Spicy");
        veryspicyrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                veryspicyradActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(veryspicyrad)
                    .addComponent(spicyrad)
                    .addComponent(mildrad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mildrad)
                .addGap(18, 18, 18)
                .addComponent(spicyrad)
                .addGap(18, 18, 18)
                .addComponent(veryspicyrad)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        saladlvl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        saladlvl.setText("Add On's");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(saladlvl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(saladlvl)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        cheeseck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cheeseck.setText("cheese  +tk20");

        eggck.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        eggck.setText(" Sausage +tk15");
        eggck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eggckActionPerformed(evt);
            }
        });

        extrack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        extrack.setText("Beef Bacon +tk60");
        extrack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extrackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cheeseck)
                    .addComponent(extrack)
                    .addComponent(eggck))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cheeseck)
                .addGap(18, 18, 18)
                .addComponent(eggck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(extrack)
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        saucelbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        saucelbl.setText("Flavour of Sauce");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(saucelbl)
                .addGap(18, 18, 18))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(saucelbl)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        lessrad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lessrad.setText("Chilli Sauce");
        lessrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessradActionPerformed(evt);
            }
        });

        regularrad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        regularrad.setText("Sweet Sauce");
        regularrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regularradActionPerformed(evt);
            }
        });

        morerad.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        morerad.setText("Ginger Sauce");
        morerad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreradActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lessrad)
                    .addComponent(regularrad)
                    .addComponent(morerad))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lessrad)
                .addGap(18, 18, 18)
                .addComponent(regularrad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(morerad)
                .addContainerGap())
        );

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton3.setText("Pay");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton4.setText("Exit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Price ", "Quantity", "Total"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        quantitylbl.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        quantitylbl.setText("Quantity");

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText("Add");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel10.setText("Balance");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Payment");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Payment");

        balancetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balancetxtActionPerformed(evt);
            }
        });

        paymenttxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymenttxtActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText("Order Status");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setText("Remove");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        Total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Total.setText("Total");

        totaltxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totaltxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(353, 353, 353)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 39, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addComponent(jButton8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(quantitylbl)
                                .addGap(18, 18, 18)
                                .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(432, 432, 432)
                                .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jButton7)
                                .addGap(60, 60, 60)
                                .addComponent(jButton2)
                                .addGap(129, 129, 129)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(78, 78, 78)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymenttxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balancetxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(209, 209, 209)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(1022, Short.MAX_VALUE)
                    .addComponent(jLabel13)
                    .addGap(285, 285, 285)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(quantitylbl)
                                    .addComponent(quantitytxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addGap(15, 15, 15)
                                .addComponent(Total)
                                .addGap(26, 26, 26))
                            .addComponent(totaltxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton2)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jLabel14))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(paymenttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(balancetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 20, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(495, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(221, 221, 221)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spicyradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spicyradActionPerformed
        // TODO add your handling code here:
        if (spicyrad.isSelected()) {
            mildrad.setSelected(false);
            veryspicyrad.setSelected(false);

        }
    }//GEN-LAST:event_spicyradActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        beefrad.setSelected(false);
        chickenrad.setSelected(false);
        veggierad.setSelected(false);
        turkeyrad.setSelected(false);

        mildrad.setSelected(false);
        spicyrad.setSelected(false);
        veryspicyrad.setSelected(false);
        //doublerad.setSelected(false);

        cheeseck.setSelected(false);
        extrack.setSelected(false);
        eggck.setSelected(false);
        jTable1.resetKeyboardActions();

//        cheeseck.setSelected(false);
//        bbqck.setSelected(false);
//        pattyck.setSelected(false);
//        eggck.setSelected(false);
        lessrad.setSelected(false);
        morerad.setSelected(false);
        regularrad.setSelected(false);

        //totaltxt.setText(" ");
        //taxtxt.setText(" ");
        //subtotaltxt.setText(" ");
        paymenttxt.setText(" ");
        balancetxt.setText(" ");
        quantitytxt.setToolTipText(" ");
        totaltxt.setText(" ");

        DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
        dm.getDataVector().removeAllElements();
        dm.fireTableDataChanged();
        
      
        
        


    }//GEN-LAST:event_jButton2ActionPerformed

    private void beefradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beefradActionPerformed
        // TODO add your handling code here
        if (beefrad.isSelected()) {
            chickenrad.setSelected(false);
            veggierad.setSelected(false);
            turkeyrad.setSelected(false);
        }

    }//GEN-LAST:event_beefradActionPerformed

    private void chickenradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chickenradActionPerformed
        // TODO add your handling code here:
        if (chickenrad.isSelected()) {
            beefrad.setSelected(false);
            veggierad.setSelected(false);
            turkeyrad.setSelected(false);

        }
    }//GEN-LAST:event_chickenradActionPerformed

    private void veggieradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veggieradActionPerformed
        // TODO add your handling code here:
        if (veggierad.isSelected()) {
            beefrad.setSelected(false);
            chickenrad.setSelected(false);
            turkeyrad.setSelected(false);

        }

    }//GEN-LAST:event_veggieradActionPerformed

    private void turkeyradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_turkeyradActionPerformed
        // TODO add your handling code here:
        if (turkeyrad.isSelected()) {
            beefrad.setSelected(false);
            chickenrad.setSelected(false);
            veggierad.setSelected(false);

        }
    }//GEN-LAST:event_turkeyradActionPerformed

    private void mildradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mildradActionPerformed
        // TODO add your handling code here:
        if (mildrad.isSelected()) {
            spicyrad.setSelected(false);
            veryspicyrad.setSelected(false);
        }
    }//GEN-LAST:event_mildradActionPerformed

    private void veryspicyradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_veryspicyradActionPerformed
        // TODO add your handling code here:
        if (veryspicyrad.isSelected()) {
            mildrad.setSelected(false);
            spicyrad.setSelected(false);
        }
    }//GEN-LAST:event_veryspicyradActionPerformed

    private void lessradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessradActionPerformed
        // TODO add your handling code here:
        if (lessrad.isSelected()) {
            morerad.setSelected(false);
            regularrad.setSelected(false);

        }

    }//GEN-LAST:event_lessradActionPerformed

    private void regularradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regularradActionPerformed
        // TODO add your handling code here:
        if (regularrad.isSelected()) {
            morerad.setSelected(false);
            lessrad.setSelected(false);

        }
    }//GEN-LAST:event_regularradActionPerformed

    private void moreradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreradActionPerformed
        // TODO add your handling code here:
        if (morerad.isSelected()) {
            regularrad.setSelected(false);
            lessrad.setSelected(false);

        }
    }//GEN-LAST:event_moreradActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (beefrad.isSelected() == true) {
            item = "Beef Burger";
            price = 100;
        } else if (chickenrad.isSelected() == true) {
            item = "Chicken Burger";
            price = 90;
        } else if (veggierad.isSelected() == true) {
            item = "Pasta";
            price = 250;
        } else if (turkeyrad.isSelected() == true) {
            item = "Special Pizza";
            price = 500;
        }

        int itemprice = 0;
        int quantity = Integer.parseInt(quantitytxt.getValue().toString());
        //nt itemprice;
        if (quantity <= 0) {
            JOptionPane.showMessageDialog(this, "Please select a valid quantity");
        } else if (eggck.isSelected() || cheeseck.isSelected() || extrack.isSelected()) {
            //itemprice= quantity * (price+20);
            if (eggck.isSelected()) {
                itemprice = quantity * (price + 15);
            }
            if (cheeseck.isSelected()) {
                itemprice = quantity * (price + 20);
            }
            if (extrack.isSelected()) {
                itemprice = quantity * (price + 60);
            }
            if (extrack.isSelected() && cheeseck.isSelected()) {
                itemprice = quantity * (price + 80);
            }
            if (extrack.isSelected() && eggck.isSelected()) {
                itemprice = quantity * (price + 75);
            }
            if (cheeseck.isSelected() && eggck.isSelected()) {
                itemprice = quantity * (price + 35);
            }

        } else {
            itemprice = quantity * price;
        }
        model = (DefaultTableModel) jTable1.getModel();

        if (quantity > 0) {
            model.addRow(new Object[]{
                item,
                price,
                quantity,
                itemprice

            });
        }

        int sum = 0;
        for (int a = 0; a < jTable1.getRowCount(); a++) {
            sum = sum + Integer.parseInt(jTable1.getValueAt(a, 3).toString());

        }
        totaltxt.setText(Integer.toString(sum));


    }//GEN-LAST:event_jButton6ActionPerformed

    private void balancetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balancetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_balancetxtActionPerformed

    private void paymenttxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymenttxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymenttxtActionPerformed

    
    
    public void sales() {
        int lastid = 0;
        try {
            String url="jdbc:mysql://127.0.0.1/hotfood";
            String user="root";
            String password="";
            Class.forName("com.mysql.jdbc.Driver");
            con = (Connection) DriverManager.getConnection(url, user, password);

            String total = totaltxt.getText();
            String balance = balancetxt.getText();
            String payment = paymenttxt.getText();

            String query = "insert into sales (id,subtotal,pay,bal)values('"+x+"',?,?,?)";
            pst = con.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, total);
            pst.setString(2, payment);
            pst.setString(3, balance);
            pst.executeUpdate();

            ResultSet rs = pst.getGeneratedKeys();

            if (rs.next()) {
                lastid = rs.getInt(1);

            }
            int row = jTable1.getRowCount();

            String query1 = "insert into sales_product (id,sales_id,prodname,price,qty,total)values('"+x+"',?,?,?,?,?)";
            pst1 = con.prepareStatement(query1);

            String prodname = "";
            int price;
            int qty;
            int tot = 0;

            for (int i = 0; i < jTable1.getRowCount(); i++) {
                prodname = (String) jTable1.getValueAt(i, 0);
                price = (int) jTable1.getValueAt(i, 1);
                qty = (int) jTable1.getValueAt(i, 2);
                tot = (int) jTable1.getValueAt(i, 3);

                pst1.setInt(1, lastid);
                pst1.setString(2, prodname);
                pst1.setInt(3, price);
                pst1.setInt(4, qty);
                pst1.setInt(5, tot);
                pst1.executeUpdate();
            }
            String s= "processing";
            String query3="insert into orderstatus (OrderID, Status) values ('"+x+"','"+s+"')";

                    java.sql.Statement statement = con.createStatement();

            
                    statement.executeUpdate(query3); 
            JOptionPane.showMessageDialog(this, " Sales Completed and Your OrderID is " + x);

           

            //x++;
//            JOptionPane.showMessageDialog(this," Sales Completed....."
//                    + " Your OrderID is 1 ");
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null,"Something went wrong");
        }

        x++;
        //jTable1.setRowHeight(0);
    }


    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        View_orderStatus view = new View_orderStatus();
        view.setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //int bal;
        int tot = Integer.parseInt(totaltxt.getText());
        int pay = Integer.parseInt(paymenttxt.getText());
        int bal = 0;
        if (tot == pay) {
            bal = 0;
             balancetxt.setText(String.valueOf(bal));
             sales();
        } else if(pay>tot){
            bal = pay - tot; 
             balancetxt.setText(String.valueOf(bal));
        }
        else {
            JOptionPane.showMessageDialog(this, "You have to pay "+ (tot-pay)+ " taka more");
        }
       

        


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
            if(jTable1.getSelectedRow() != -1) {
               // remove selected row from the model
              model.removeRow(jTable1.getSelectedRow());
            }
            else {
                JOptionPane.showMessageDialog(this, "Please select a row");
            }
        
        int sum = 0;

        for (int a = 0; a < jTable1.getRowCount(); a++) {
            sum = sum + Integer.parseInt(jTable1.getValueAt(a, 3).toString());

        }
        totaltxt.setText(Integer.toString(sum));
    }//GEN-LAST:event_jButton8ActionPerformed

    private void totaltxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totaltxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totaltxtActionPerformed

    private void eggckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eggckActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eggckActionPerformed

    private void extrackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extrackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_extrackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_pannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_pannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_pannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_pannel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_pannel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total;
    private javax.swing.JTextField balancetxt;
    private javax.swing.JRadioButton beefrad;
    private javax.swing.JLabel bunlbl;
    private javax.swing.JCheckBox cheeseck;
    private javax.swing.JRadioButton chickenrad;
    private javax.swing.JCheckBox eggck;
    private javax.swing.JCheckBox extrack;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton lessrad;
    private javax.swing.JRadioButton mildrad;
    private javax.swing.JRadioButton morerad;
    private javax.swing.JTextField paymenttxt;
    private javax.swing.JLabel quantitylbl;
    private javax.swing.JSpinner quantitytxt;
    private javax.swing.JRadioButton regularrad;
    private javax.swing.JLabel saladlvl;
    private javax.swing.JLabel saucelbl;
    private javax.swing.JRadioButton spicyrad;
    private javax.swing.JTextField totaltxt;
    private javax.swing.JRadioButton turkeyrad;
    private javax.swing.JRadioButton veggierad;
    private javax.swing.JRadioButton veryspicyrad;
    // End of variables declaration//GEN-END:variables

}
